/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
}

class FmodSFX {
    public static inline var NoteHitPress:String = "event:/SFX/NoteHitPress";
    public static inline var NoteMissPress:String = "event:/SFX/NoteMissPress";
}
